version: '3.8'
services:

  mailserver:
    image: ixdotai/smtp:latest
    network_mode: host
    env_file:
      - ./config/.env.docker
    ports:
      - "25:25"

  redis:
    image: redis:latest
    env_file:
      - ./config/.env.docker
    ports:
      - "6379:6379"
    volumes:
      - /docker/redis/data:/root/redis
      - /docker/redis/redis.conf:/usr/local/etc/redis/redis.conf

