import { ItemAntiFlag, ItemAttribute, ItemFlag, ItemImmuneFlag, ItemLimitType, ItemMaskType, ItemMaskTypeCostume, ItemMaskTypeDragonStone, ItemMaskTypeEquipmentArmor, ItemMaskTypeEquipmentJewelry, ItemMaskTypeEquipmentWeapon, ItemMaskTypeEtc, ItemMaskTypeFishingPick, ItemMaskTypeMountPet, ItemMaskTypePotion, ItemMaskTypeSkill, ItemMaskTypeTuning, ItemMaskTypeUnique, ItemSpecialActionType, ItemSpecialType, ItemType, ItemTypeArmor, ItemTypeCostume, ItemTypeDragonSoul, ItemTypeExtract, ItemTypeFish, ItemTypeGacha, ItemTypeGiftbox, ItemTypeLottery, ItemTypeMaterial, ItemTypeMedium, ItemTypeMercenary, ItemTypeMetin, ItemTypePassive, ItemTypePet, ItemTypeQuest, ItemTypeResource, ItemTypeSoul, ItemTypeSpecial, ItemTypeUnique, ItemTypeUse, ItemTypeWeapon, ItemWearFlag } from "./Item";

export enum GameItemProtoFormat {
  DEFAULT,
  VERSION_2017,
  VERSION_2022
}

export enum GameItemSpecialType {
  NORMAL = ItemSpecialType.DEFAULT,
  PCT = ItemSpecialType.MULTIPLE,
  QUEST = ItemSpecialType.QUEST,
  SPECIAL = ItemSpecialType.SPECIAL,
  ATTR = ItemSpecialType.ATTRIBUTE
}

export enum GameItemSpecialActionType {
  EXP = ItemSpecialActionType.EXP,
  "경험치" = ItemSpecialActionType.EXP,
  MOB = ItemSpecialActionType.MOB,
  GROUP = ItemSpecialActionType.MOB_GROUP,
  SLOW = ItemSpecialActionType.SLOW,
  POISON = ItemSpecialActionType.POISON,
  DRAIN_HP = ItemSpecialActionType.DRAIN_HP,
}

/*****************************************************************************
 * Type
 *****************************************************************************/
export enum GameItemProtoType {
  ITEM_NONE = ItemType.NONE,
  ITEM_WEAPON = ItemType.WEAPON,
  ITEM_ARMOR = ItemType.ARMOR,
  ITEM_USE = ItemType.USE,
  ITEM_AUTOUSE = ItemType.AUTOUSE,
  ITEM_MATERIAL = ItemType.MATERIAL,
  ITEM_SPECIAL = ItemType.SPECIAL,
  ITEM_TOOL = ItemType.TOOL,
  ITEM_LOTTERY = ItemType.LOTTERY,
  ITEM_ELK = ItemType.ELK,
  ITEM_METIN = ItemType.METIN,
  ITEM_CONTAINER = ItemType.CONTAINER,
  ITEM_FISH = ItemType.FISH,
  ITEM_ROD = ItemType.ROD,
  ITEM_RESOURCE = ItemType.RESOURCE,
  ITEM_CAMPFIRE = ItemType.CAMPFIRE,
  ITEM_UNIQUE = ItemType.UNIQUE,
  ITEM_SKILLBOOK = ItemType.SKILLBOOK,
  ITEM_QUEST = ItemType.QUEST,
  ITEM_POLYMORPH = ItemType.POLYMORPH,
  ITEM_TREASURE_BOX = ItemType.TREASURE_BOX,
  ITEM_TREASURE_KEY = ItemType.TREASURE_KEY,
  ITEM_SKILLFORGET = ItemType.SKILLFORGET,
  ITEM_GIFTBOX = ItemType.GIFTBOX,
  ITEM_PICK = ItemType.PICK,
  ITEM_HAIR = ItemType.HAIR,
  ITEM_TOTEM = ItemType.TOTEM,
  ITEM_BLEND = ItemType.BLEND,
  ITEM_COSTUME = ItemType.COSTUME,
  ITEM_DS = ItemType.DRAGON_SOUL,
  ITEM_SPECIAL_DS = ItemType.SPECIAL_DRAGON_SOUL,
  ITEM_EXTRACT = ItemType.EXTRACT,
  ITEM_SECONDARY_COIN = ItemType.SECONDARY_COIN,
  ITEM_RING = ItemType.RING,
  ITEM_BELT = ItemType.BELT,

  // VERSION_2022
  // ITEM_PET = ItemType.PET,
  // ITEM_MEDIUM = ItemType.MEDIUM,
  // ITEM_GACHA = ItemType.GACHA,
  // ITEM_SOUL = ItemType.SOUL,
  // ITEM_PASSIVE = ItemType.PASSIVE,
  // ITEM_MERCENARY = ItemType.MERCENARY,
  // ITEM_UNK_41 = ItemType.UNKNOWN_41
}


/*****************************************************************************
 * SubType
 *****************************************************************************/
export enum GameItemProtoTypeWeapon {
  WEAPON_SWORD = ItemTypeWeapon.SWORD,
  WEAPON_DAGGER = ItemTypeWeapon.DAGGER,
  WEAPON_BOW = ItemTypeWeapon.BOW,
  WEAPON_TWO_HANDED = ItemTypeWeapon.TWO_HANDED,
  WEAPON_BELL = ItemTypeWeapon.BELL,
  WEAPON_FAN = ItemTypeWeapon.FAN,
  WEAPON_ARROW = ItemTypeWeapon.ARROW,
  WEAPON_MOUNT_SPEAR = ItemTypeWeapon.MOUNT_SPEAR,

  // VERSION_2022
  // WEAPON_CLAW = ItemTypeWeapon.CLAW,
  // WEAPON_QUIVER = ItemTypeWeapon.QUIVER,
  // WEAPON_BOUQUET = ItemTypeWeapon.BOUQUET,
}

export enum GameItemProtoTypeArmor {
  ARMOR_BODY = ItemTypeArmor.BODY,
  ARMOR_HEAD = ItemTypeArmor.HEAD,
  ARMOR_SHIELD = ItemTypeArmor.SHIELD,
  ARMOR_WRIST = ItemTypeArmor.WRIST,
  ARMOR_FOOTS = ItemTypeArmor.FOOTS,
  ARMOR_NECK = ItemTypeArmor.NECK,
  ARMOR_EAR = ItemTypeArmor.EAR,

  // VERSION_2022
  // ARMOR_PENDANT = ItemTypeArmor.PENDANT,
  // ARMOR_GLOVE = ItemTypeArmor.GLOVE,
}

export enum GameItemProtoTypeUse {
  USE_POTION = ItemTypeUse.POTION,
  USE_TALISMAN = ItemTypeUse.TALISMAN,
  USE_TUNING = ItemTypeUse.TUNING,
  USE_MOVE = ItemTypeUse.MOVE,
  USE_TREASURE_BOX = ItemTypeUse.TREASURE_BOX,
  USE_MONEYBAG = ItemTypeUse.MONEYBAG,
  USE_BAIT = ItemTypeUse.BAIT,
  USE_ABILITY_UP = ItemTypeUse.ABILITY_UP,
  USE_AFFECT = ItemTypeUse.AFFECT,
  USE_CREATE_STONE = ItemTypeUse.CREATE_STONE,
  USE_SPECIAL = ItemTypeUse.SPECIAL,
  USE_POTION_NODELAY = ItemTypeUse.POTION_NODELAY,
  USE_CLEAR = ItemTypeUse.CLEAR,
  USE_INVISIBILITY = ItemTypeUse.INVISIBILITY,
  USE_DETACHMENT = ItemTypeUse.DETACHMENT,
  USE_BUCKET = ItemTypeUse.BUCKET,
  USE_POTION_CONTINUE = ItemTypeUse.POTION_CONTINUE,
  USE_CLEAN_SOCKET = ItemTypeUse.CLEAN_SOCKET,
  USE_CHANGE_ATTRIBUTE = ItemTypeUse.CHANGE_ATTRIBUTE,
  USE_ADD_ATTRIBUTE = ItemTypeUse.ADD_ATTRIBUTE,
  USE_ADD_ACCESSORY_SOCKET = ItemTypeUse.ADD_ACCESSORY_SOCKET,
  USE_PUT_INTO_ACCESSORY_SOCKET = ItemTypeUse.PUT_INTO_ACCESSORY_SOCKET,
  USE_ADD_ATTRIBUTE2 = ItemTypeUse.ADD_ATTRIBUTE2,
  USE_RECIPE = ItemTypeUse.RECIPE,
  USE_CHANGE_ATTRIBUTE2 = ItemTypeUse.CHANGE_ATTRIBUTE2,
  USE_BIND = ItemTypeUse.BIND,
  USE_UNBIND = ItemTypeUse.UNBIND,
  USE_TIME_CHARGE_PER = ItemTypeUse.TIME_CHARGE_PER,
  USE_TIME_CHARGE_FIX = ItemTypeUse.TIME_CHARGE_FIX,
  USE_PUT_INTO_BELT_SOCKET = ItemTypeUse.PUT_INTO_BELT_SOCKET,
  USE_PUT_INTO_RING_SOCKET = ItemTypeUse.PUT_INTO_RING_SOCKET,

  // VERSION_2022
  // USE_CHANGE_COSTUME_ATTR = ItemTypeUse.CHANGE_COSTUME_ATTR,
  // USE_RESET_COSTUME_ATTR = ItemTypeUse.RESET_COSTUME_ATTR,
  // // UNKNOWN                                             = ItemTypeUse.UNKNOWN,
  // USE_SELECT_ATTRIBUTE = ItemTypeUse.SELECT_ATTRIBUTE,
  // // UNKNOWN                                             = ItemTypeUse.UNKNOWN,
  // USE_EMOTION_PACK = ItemTypeUse.EMOTION_PACK,
  // USE_ELEMENT_UPGRADE = ItemTypeUse.ELEMENT_UPGRADE,
  // USE_ELEMENT_DOWNGRADE = ItemTypeUse.ELEMENT_DOWNGRADE,
  // USE_ELEMENT_CHANGE = ItemTypeUse.ELEMENT_CHANGE,
  // USE_CALL = ItemTypeUse.CALL,
  // USE_POTION_TOWER = ItemTypeUse.POTION_TOWER,
  // USE_POTION_NODELAY_TOWER = ItemTypeUse.POTION_NODELAY_TOWER,
  // USE_REMOVE_AFFECT = ItemTypeUse.REMOVE_AFFECT,
  // USE_EMOTION_TOWER = ItemTypeUse.EMOTION_TOWER,
  // USE_SECRET_DUNGEON_SCROLL = ItemTypeUse.SECRET_DUNGEON_SCROLL,
}

export enum GameItemProtoTypeMaterial {
  MATERIAL_LEATHER = ItemTypeMaterial.LEATHER,
  MATERIAL_BLOOD = ItemTypeMaterial.BLOOD,
  MATERIAL_ROOT = ItemTypeMaterial.ROOT,
  MATERIAL_NEEDLE = ItemTypeMaterial.NEEDLE,
  MATERIAL_JEWEL = ItemTypeMaterial.JEWEL,
  MATERIAL_DS_REFINE_NORMAL = ItemTypeMaterial.DRAGON_SOUL_REFINE_NORMAL,
  MATERIAL_DS_REFINE_BLESSED = ItemTypeMaterial.DRAGON_SOUL_REFINE_BLESSED,
  MATERIAL_DS_REFINE_HOLLY = ItemTypeMaterial.DRAGON_SOUL_REFINE_HOLLY,

  // VERSION_2022
  // MATERIAL_DS_CHANGE_ATTR = ItemTypeMaterial.DRAGON_SOUL_CHANGE_ATTR,
  // MATERIAL_PASSIVE_WEAPON = ItemTypeMaterial.PASSIVE_WEAPON,
  // MATERIAL_PASSIVE_ARMOR = ItemTypeMaterial.PASSIVE_ARMOR,
  // MATERIAL_PASSIVE_ACCE = ItemTypeMaterial.PASSIVE_ACCE,
  // MATERIAL_PASSIVE_ELEMENT = ItemTypeMaterial.PASSIVE_ELEMENT,
}

export enum GameItemProtoTypeSpecial {
  SPECIAL_MAP = ItemTypeSpecial.MAP,
  SPECIAL_KEY = ItemTypeSpecial.KEY,
  SPECIAL_DOC = ItemTypeSpecial.DOC,
  SPECIAL_SPIRIT = ItemTypeSpecial.SPIRIT
}

export enum GameItemProtoTypeLottery {
  LOTTERY_TICKET = ItemTypeLottery.TICKET,
  LOTTERY_INSTANT = ItemTypeLottery.INSTANT
}

export enum GameItemProtoTypeMetin {
  METIN_NORMAL = ItemTypeMetin.NORMAL,
  METIN_GOLD = ItemTypeMetin.GOLD,

  // VERSION_2022
  // METIN_SUNGMA = ItemTypeMetin.SUNGMA,
}

export enum GameItemProtoTypeFish {
  FISH_ALIVE = ItemTypeFish.ALIVE,
  FISH_DEAD = ItemTypeFish.DEAD
}

export enum GameItemProtoTypeResource {
  RESOURCE_FISHBONE = ItemTypeResource.FISHBONE,
  RESOURCE_WATERSTONEPIECE = ItemTypeResource.WATERSTONEPIECE,
  RESOURCE_WATERSTONE = ItemTypeResource.WATERSTONE,
  RESOURCE_BLOOD_PEARL = ItemTypeResource.BLOOD_PEARL,
  RESOURCE_BLUE_PEARL = ItemTypeResource.BLUE_PEARL,
  RESOURCE_WHITE_PEARL = ItemTypeResource.WHITE_PEARL,
  RESOURCE_BUCKET = ItemTypeResource.BUCKET,
  RESOURCE_CRYSTAL = ItemTypeResource.CRYSTAL,
  RESOURCE_GEM = ItemTypeResource.GEM,
  RESOURCE_STONE = ItemTypeResource.STONE,
  RESOURCE_METIN = ItemTypeResource.METIN,
  RESOURCE_ORE = ItemTypeResource.ORE,

  // VERSION_2022
  // RESOURCE_AURA = ItemTypeResource.AURA,
}

export enum GameItemProtoTypeUnique {
  UNIQUE_NONE = ItemTypeUnique.NONE,
  UNIQUE_BOOK = ItemTypeUnique.BOOK,
  UNIQUE_SPECIAL_RIDE = ItemTypeUnique.SPECIAL_RIDE,
  UNIQUE_3 = ItemTypeUnique.SPECIAL_MOUNT_RIDE,
  UNIQUE_4 = ItemTypeUnique.UNIQUE_4,
  UNIQUE_5 = ItemTypeUnique.UNIQUE_5,
  UNIQUE_6 = ItemTypeUnique.UNIQUE_6,
  UNIQUE_7 = ItemTypeUnique.UNIQUE_7,
  UNIQUE_8 = ItemTypeUnique.UNIQUE_8,
  UNIQUE_9 = ItemTypeUnique.UNIQUE_9,
  USE_SPECIAL = ItemTypeUnique.SPECIAL,
}

export enum GameItemProtoTypeQuest {
  QUEST_NONE = ItemTypeQuest.NONE,
  QUEST_PET_PAY = ItemTypeQuest.PET_PAY,
  QUEST_WARP = ItemTypeQuest.WARP,
}

export enum GameItemProtoTypeGiftbox {
  UNK23_1 = ItemTypeGiftbox.UNKNOWN_1,
  UNK23_2 = ItemTypeGiftbox.UNKNOWN_2
}

export enum GameItemProtoTypeCostume {
  COSTUME_BODY = ItemTypeCostume.BODY,
  COSTUME_HAIR = ItemTypeCostume.HAIR,

  // VERSION_2022
  // COSTUME_MOUNT = ItemTypeCostume.MOUNT,
  // COSTUME_ACCE = ItemTypeCostume.ACCE,
  // COSTUME_WEAPON = ItemTypeCostume.WEAPON,
  // COSTUME_AURA = ItemTypeCostume.AURA,
}

export enum GameItemProtoTypeDragonSoul {
  DS_SLOT1 = ItemTypeDragonSoul.SLOT1,
  DS_SLOT2 = ItemTypeDragonSoul.SLOT2,
  DS_SLOT3 = ItemTypeDragonSoul.SLOT3,
  DS_SLOT4 = ItemTypeDragonSoul.SLOT4,
  DS_SLOT5 = ItemTypeDragonSoul.SLOT5,
  DS_SLOT6 = ItemTypeDragonSoul.SLOT6,
}

export enum GameItemProtoTypeExtract {
  EXTRACT_DRAGON_SOUL = ItemTypeExtract.DRAGON_SOUL,
  EXTRACT_DRAGON_HEART = ItemTypeExtract.DRAGON_HEART
}

export enum GameItemProtoTypePet {
  PET_EGG = ItemTypePet.EGG,
  PET_UPBRINGING = ItemTypePet.UPBRINGING,
  PET_BAG = ItemTypePet.BAG,
  PET_FEEDSTUFF = ItemTypePet.FEEDSTUFF,
  PET_SKILL = ItemTypePet.SKILL,
  PET_SKILL_DEL_BOOK = ItemTypePet.SKILL_DEL_BOOK,
  PET_NAME_CHANGE = ItemTypePet.NAME_CHANGE,
  PET_EXPFOOD = ItemTypePet.EXPFOOD,
  PET_SKILL_ALL_DEL_BOOK = ItemTypePet.SKILL_ALL_DEL_BOOK,
  PET_EXPFOOD_PER = ItemTypePet.EXPFOOD_PER,
  PET_ATTR_DETERMINE = ItemTypePet.ATTR_DETERMINE,
  PET_ATTR_CHANGE = ItemTypePet.ATTR_CHANGE,
  PET_PAY = ItemTypePet.PAY,
  PET_PRIMIUM_FEEDSTUFF = ItemTypePet.PRIMIUM_FEEDSTUFF,
  PET_ITEM_TYPE = ItemTypePet.ITEM_TYPE
}

export enum GameItemProtoTypeMedium {
  MEDIUM_MOVE_COSTUME_ATTR = ItemTypeMedium.MOVE_COSTUME_ATTR,
  MEDIUM_MOVE_ACCE_ATTR = ItemTypeMedium.MOVE_ACCE_ATTR
}

export enum GameItemProtoTypeGacha {
  USE_GACHA = ItemTypeGacha.USE,
  // SPECIAL_GACHA = ItemTypeGacha.SPECIAL,
  SPECIAL_LUCKY_BOX_GACHA = ItemTypeGacha.SPECIAL_LUCKY_BOX,
  GEM_LUCKY_BOX_GACHA = ItemTypeGacha.GEM_LUCKY_BOX,

}

export enum GameItemProtoTypeSoul {
  SOUL_RED = ItemTypeSoul.RED,
  SOUL_BLUE = ItemTypeSoul.BLUE
}

export enum GameItemProtoTypeMercenary {
  MERCENARY_0 = ItemTypeMercenary.MERCENARY_0,
  MERCENARY_1 = ItemTypeMercenary.MERCENARY_1,
  MERCENARY_2 = ItemTypeMercenary.MERCENARY_2,
  MERCENARY_3 = ItemTypeMercenary.MERCENARY_3,
  MERCENARY_4 = ItemTypeMercenary.MERCENARY_4,
  MERCENARY_5 = ItemTypeMercenary.MERCENARY_5,
  MERCENARY_6 = ItemTypeMercenary.MERCENARY_6,
}

export enum GameItemProtoTypePassive {
  PASSIVE_JOB = ItemTypePassive.JOB
}

export const GameItemProtoTypeSubTypes = {
  [GameItemProtoType.ITEM_NONE]: {},
  [GameItemProtoType.ITEM_WEAPON]: GameItemProtoTypeWeapon,
  [GameItemProtoType.ITEM_ARMOR]: GameItemProtoTypeArmor,
  [GameItemProtoType.ITEM_USE]: GameItemProtoTypeUse,
  [GameItemProtoType.ITEM_AUTOUSE]: {},
  [GameItemProtoType.ITEM_MATERIAL]: GameItemProtoTypeMaterial,
  [GameItemProtoType.ITEM_SPECIAL]: GameItemProtoTypeSpecial,
  [GameItemProtoType.ITEM_TOOL]: {},
  [GameItemProtoType.ITEM_LOTTERY]: GameItemProtoTypeLottery,
  [GameItemProtoType.ITEM_ELK]: {},
  [GameItemProtoType.ITEM_METIN]: GameItemProtoTypeMetin,
  [GameItemProtoType.ITEM_CONTAINER]: {},
  [GameItemProtoType.ITEM_FISH]: GameItemProtoTypeFish,
  [GameItemProtoType.ITEM_ROD]: {},
  [GameItemProtoType.ITEM_RESOURCE]: GameItemProtoTypeResource,
  [GameItemProtoType.ITEM_CAMPFIRE]: {},
  [GameItemProtoType.ITEM_UNIQUE]: GameItemProtoTypeUnique,
  [GameItemProtoType.ITEM_SKILLBOOK]: {},
  [GameItemProtoType.ITEM_QUEST]: GameItemProtoTypeQuest,
  [GameItemProtoType.ITEM_POLYMORPH]: {},
  [GameItemProtoType.ITEM_TREASURE_BOX]: {},
  [GameItemProtoType.ITEM_TREASURE_KEY]: {},
  [GameItemProtoType.ITEM_SKILLFORGET]: {},
  [GameItemProtoType.ITEM_GIFTBOX]: GameItemProtoTypeGiftbox,
  [GameItemProtoType.ITEM_PICK]: {},
  [GameItemProtoType.ITEM_HAIR]: {},
  [GameItemProtoType.ITEM_TOTEM]: {},
  [GameItemProtoType.ITEM_BLEND]: {},
  [GameItemProtoType.ITEM_COSTUME]: GameItemProtoTypeCostume,
  [GameItemProtoType.ITEM_DS]: GameItemProtoTypeDragonSoul,
  [GameItemProtoType.ITEM_SPECIAL_DS]: {},
  [GameItemProtoType.ITEM_EXTRACT]: GameItemProtoTypeExtract,
  [GameItemProtoType.ITEM_SECONDARY_COIN]: {},
  [GameItemProtoType.ITEM_RING]: {},
  [GameItemProtoType.ITEM_BELT]: {},

  // VERSION_2022
  // [GameItemProtoType.ITEM_PET]: GameItemProtoTypePet,
  // [GameItemProtoType.ITEM_MEDIUM]: GameItemProtoTypeMedium,
  // [GameItemProtoType.ITEM_GACHA]: GameItemProtoTypeGacha,
  // [GameItemProtoType.ITEM_SOUL]: GameItemProtoTypeSoul,
  // [GameItemProtoType.ITEM_PASSIVE]: GameItemProtoTypePassive,
  // [GameItemProtoType.ITEM_MERCENARY]: GameItemProtoTypeMercenary,
  // [GameItemProtoType.ITEM_UNK_41]: {},
}

/*****************************************************************************
 * Flag
 *****************************************************************************/
export enum GameItemProtoFlag {
  NONE = ItemFlag.NONE,
  ITEM_TUNABLE = ItemFlag.REFINEABLE,
  ITEM_SAVE = ItemFlag.SAVE,
  ITEM_STACKABLE = ItemFlag.STACKABLE,
  COUNT_PER_1GOLD = ItemFlag.COUNT_PER_1GOLD,
  ITEM_SLOW_QUERY = ItemFlag.SLOW_QUERY,
  ITEM_RARE = ItemFlag.RARE,
  ITEM_UNIQUE = ItemFlag.UNIQUE,
  ITEM_MAKECOUNT = ItemFlag.MAKECOUNT,
  ITEM_IRREMOVABLE = ItemFlag.IRREMOVABLE,
  CONFIRM_WHEN_USE = ItemFlag.CONFIRM_WHEN_USE,
  QUEST_USE = ItemFlag.QUEST_USE,
  QUEST_USE_MULTIPLE = ItemFlag.QUEST_USE_MULTIPLE,
  QUEST_GIVE = ItemFlag.QUEST_GIVE,
  LOG = ItemFlag.LOG,
  ITEM_APPLICABLE = ItemFlag.APPLICABLE,
}


/*****************************************************************************
 * Anti flag
 *****************************************************************************/
export enum GameItemProtoAntiFlag {
  NONE = ItemAntiFlag.NONE,
  ANTI_FEMALE = ItemAntiFlag.FEMALE,
  ANTI_MALE = ItemAntiFlag.MALE,
  ANTI_MUSA = ItemAntiFlag.WARRIOR,
  ANTI_ASSASSIN = ItemAntiFlag.ASSASSIN,
  ANTI_SURA = ItemAntiFlag.SURA,
  ANTI_MUDANG = ItemAntiFlag.SHAMAN,
  ANTI_GET = ItemAntiFlag.GET,
  ANTI_DROP = ItemAntiFlag.DROP,
  ANTI_SELL = ItemAntiFlag.SELL,
  ANTI_EMPIRE_A = ItemAntiFlag.EMPIRE_A,
  ANTI_EMPIRE_B = ItemAntiFlag.EMPIRE_B,
  ANTI_EMPIRE_C = ItemAntiFlag.EMPIRE_C,
  ANTI_SAVE = ItemAntiFlag.SAVE,
  ANTI_GIVE = ItemAntiFlag.GIVE,
  ANTI_PKDROP = ItemAntiFlag.PKDROP,
  ANTI_STACK = ItemAntiFlag.STACK,
  ANTI_MYSHOP = ItemAntiFlag.MYSHOP,
  ANTI_SAFEBOX = ItemAntiFlag.SAFEBOX,

  // VERSION_2022
  // ANTI_WOLFMAN = ItemAntiFlag.WOLFMAN,
  // ANTI_RT_REMOVE = ItemAntiFlag.RT_REMOVE,
  // ANTI_QUICKSLOT = ItemAntiFlag.QUICKSLOT,
  // ANTI_CHANGELOOK = ItemAntiFlag.CHANGELOOK,
  // ANTI_REINFORCE = ItemAntiFlag.REINFORCE,
  // ANTI_ENCHANT = ItemAntiFlag.ENCHANT,
  // ANTI_ENERGY = ItemAntiFlag.ENERGY,
  // ANTI_PETFEED = ItemAntiFlag.PETFEED,
  // ANTI_APPLY = ItemAntiFlag.APPLY,
  // ANTI_ACCE = ItemAntiFlag.ACCE,
  // ANTI_MAIL = ItemAntiFlag.MAIL,
}


/*****************************************************************************
 * Wear flag
 *****************************************************************************/
export enum GameItemProtoWearFlag {
  NONE = ItemWearFlag.NONE,
  WEAR_BODY = ItemWearFlag.BODY,
  WEAR_HEAD = ItemWearFlag.HEAD,
  WEAR_FOOTS = ItemWearFlag.FOOTS,
  WEAR_WRIST = ItemWearFlag.WRIST,
  WEAR_WEAPON = ItemWearFlag.WEAPON,
  WEAR_NECK = ItemWearFlag.NECK,
  WEAR_EAR = ItemWearFlag.EAR,
  WEAR_UNIQUE = ItemWearFlag.UNIQUE,
  WEAR_SHIELD = ItemWearFlag.SHIELD,
  WEAR_ARROW = ItemWearFlag.ARROW,
  WEAR_HAIR = ItemWearFlag.HAIR,
  WEAR_ABILITY = ItemWearFlag.ABILITY,

  // VERSION_2022
  // WEAR_PENDANT = ItemWearFlag.PENDANT,
  // WEAR_GLOVE = ItemWearFlag.GLOVE,
}


/*****************************************************************************
 * Immune flag
 *****************************************************************************/
export enum GameItemProtoImmuneFlag {
  NONE = ItemImmuneFlag.NONE,
  PARA = ItemImmuneFlag.PARA,
  CURSE = ItemImmuneFlag.CURSE,
  STUN = ItemImmuneFlag.STUN,
  SLEEP = ItemImmuneFlag.SLEEP,
  SLOW = ItemImmuneFlag.SLOW,
  POISON = ItemImmuneFlag.POISON,
  TERROR = ItemImmuneFlag.TERROR
}


/*****************************************************************************
 * Limit types
 *****************************************************************************/
export enum GameItemProtoLimitType {
  LIMIT_NONE = ItemLimitType.NONE,
  LEVEL = ItemLimitType.LEVEL,
  LIMIT_STR = ItemLimitType.STR,
  LIMIT_DEX = ItemLimitType.DEX,
  LIMIT_INT = ItemLimitType.INT,
  LIMIT_CON = ItemLimitType.CON,
  REAL_TIME = ItemLimitType.REAL_TIME,
  REAL_TIME_FIRST_USE = ItemLimitType.REAL_TIME_FIRST_USE,
  TIMER_BASED_ON_WEAR = ItemLimitType.TIMER_BASED_ON_WEAR,

  // VERSION_2022
  // NEWWORLD_LEVEL = ItemLimitType.NEWWORLD_LEVEL,
  // DURATION = ItemLimitType.DURATION
}


/*****************************************************************************
 * Apply types
 *****************************************************************************/
export enum GameItemProtoApplyType {
  APPLY_NONE = ItemAttribute.NONE,
  APPLY_MAX_HP = ItemAttribute.MAX_HP,
  APPLY_MAX_SP = ItemAttribute.MAX_SP,
  APPLY_CON = ItemAttribute.CON,
  APPLY_INT = ItemAttribute.INT,
  APPLY_STR = ItemAttribute.STR,
  APPLY_DEX = ItemAttribute.DEX,
  APPLY_ATT_SPEED = ItemAttribute.ATTACK_SPEED,
  APPLY_MOV_SPEED = ItemAttribute.MOVE_SPEED,
  APPLY_CAST_SPEED = ItemAttribute.CAST_SPEED,
  APPLY_HP_REGEN = ItemAttribute.HP_REGEN,
  APPLY_SP_REGEN = ItemAttribute.SP_REGEN,
  APPLY_POISON_PCT = ItemAttribute.POISON_PCT,
  APPLY_STUN_PCT = ItemAttribute.STUN_PCT,
  APPLY_SLOW_PCT = ItemAttribute.SLOW_PCT,
  APPLY_CRITICAL_PCT = ItemAttribute.CRITICAL_PCT,
  APPLY_PENETRATE_PCT = ItemAttribute.PENETRATE_PCT,
  APPLY_ATTBONUS_HUMAN = ItemAttribute.ATTBONUS_HUMAN,
  APPLY_ATTBONUS_ANIMAL = ItemAttribute.ATTBONUS_ANIMAL,
  APPLY_ATTBONUS_ORC = ItemAttribute.ATTBONUS_ORC,
  APPLY_ATTBONUS_MILGYO = ItemAttribute.ATTBONUS_MILGYO,
  APPLY_ATTBONUS_UNDEAD = ItemAttribute.ATTBONUS_UNDEAD,
  APPLY_ATTBONUS_DEVIL = ItemAttribute.ATTBONUS_DEVIL,
  APPLY_STEAL_HP = ItemAttribute.STEAL_HP,
  APPLY_STEAL_SP = ItemAttribute.STEAL_SP,
  APPLY_MANA_BURN_PCT = ItemAttribute.MANA_BURN_PCT,
  APPLY_DAMAGE_SP_RECOVER = ItemAttribute.DAMAGE_SP_RECOVER,
  APPLY_BLOCK = ItemAttribute.BLOCK,
  APPLY_DODGE = ItemAttribute.DODGE,
  APPLY_RESIST_SWORD = ItemAttribute.RESIST_SWORD,
  APPLY_RESIST_TWOHAND = ItemAttribute.RESIST_TWOHAND,
  APPLY_RESIST_DAGGER = ItemAttribute.RESIST_DAGGER,
  APPLY_RESIST_BELL = ItemAttribute.RESIST_BELL,
  APPLY_RESIST_FAN = ItemAttribute.RESIST_FAN,
  APPLY_RESIST_BOW = ItemAttribute.RESIST_BOW,
  APPLY_RESIST_FIRE = ItemAttribute.RESIST_FIRE,
  APPLY_RESIST_ELEC = ItemAttribute.RESIST_ELEC,
  APPLY_RESIST_MAGIC = ItemAttribute.RESIST_MAGIC,
  APPLY_RESIST_WIND = ItemAttribute.RESIST_WIND,
  APPLY_REFLECT_MELEE = ItemAttribute.REFLECT_MELEE,
  APPLY_REFLECT_CURSE = ItemAttribute.REFLECT_CURSE,
  APPLY_POISON_REDUCE = ItemAttribute.POISON_REDUCE,
  APPLY_KILL_SP_RECOVER = ItemAttribute.KILL_SP_RECOVER,
  APPLY_EXP_DOUBLE_BONUS = ItemAttribute.EXP_DOUBLE_BONUS,
  APPLY_GOLD_DOUBLE_BONUS = ItemAttribute.GOLD_DOUBLE_BONUS,
  APPLY_ITEM_DROP_BONUS = ItemAttribute.ITEM_DROP_BONUS,
  APPLY_POTION_BONUS = ItemAttribute.POTION_BONUS,
  APPLY_KILL_HP_RECOVER = ItemAttribute.KILL_HP_RECOVER,
  APPLY_IMMUNE_STUN = ItemAttribute.IMMUNE_STUN,
  APPLY_IMMUNE_SLOW = ItemAttribute.IMMUNE_SLOW,
  APPLY_IMMUNE_FALL = ItemAttribute.IMMUNE_FALL,
  APPLY_SKILL = ItemAttribute.SKILL,
  APPLY_BOW_DISTANCE = ItemAttribute.ADD_BOW_DISTANCE,
  APPLY_ATT_GRADE_BONUS = ItemAttribute.ATT_BONUS,
  APPLY_DEF_GRADE_BONUS = ItemAttribute.DEF_BONUS,
  APPLY_MAGIC_ATT_GRADE = ItemAttribute.MAGIC_ATT_GRADE,
  APPLY_MAGIC_DEF_GRADE = ItemAttribute.MAGIC_DEF_GRADE,
  APPLY_CURSE_PCT = ItemAttribute.CURSE_PCT,
  APPLY_MAX_STAMINA = ItemAttribute.MAX_STAMINA,
  APPLY_ATTBONUS_WARRIOR = ItemAttribute.ATT_BONUS_TO_WARRIOR,
  APPLY_ATTBONUS_ASSASSIN = ItemAttribute.ATT_BONUS_TO_ASSASSIN,
  APPLY_ATTBONUS_SURA = ItemAttribute.ATT_BONUS_TO_SURA,
  APPLY_ATTBONUS_SHAMAN = ItemAttribute.ATT_BONUS_TO_SHAMAN,
  APPLY_ATTBONUS_MONSTER = ItemAttribute.ATT_BONUS_TO_MONSTER,
  APPLY_MALL_ATTBONUS = ItemAttribute.MALL_ATTBONUS,
  APPLY_MALL_DEFBONUS = ItemAttribute.MALL_DEFBONUS,
  APPLY_MALL_EXPBONUS = ItemAttribute.MALL_EXPBONUS,
  APPLY_MALL_ITEMBONUS = ItemAttribute.MALL_ITEMBONUS,
  APPLY_MALL_GOLDBONUS = ItemAttribute.MALL_GOLDBONUS,
  APPLY_MAX_HP_PCT = ItemAttribute.MAX_HP_PCT,
  APPLY_MAX_SP_PCT = ItemAttribute.MAX_SP_PCT,
  APPLY_SKILL_DAMAGE_BONUS = ItemAttribute.SKILL_DAMAGE_BONUS,
  APPLY_NORMAL_HIT_DAMAGE_BONUS = ItemAttribute.NORMAL_HIT_DAMAGE_BONUS,
  APPLY_SKILL_DEFEND_BONUS = ItemAttribute.SKILL_DEFEND_BONUS,
  APPLY_NORMAL_HIT_DEFEND_BONUS = ItemAttribute.NORMAL_HIT_DEFEND_BONUS,
  APPLY_EXTRACT_HP_PCT = ItemAttribute.EXTRACT_HP_PCT,
  APPLY_PC_BANG_EXP_BONUS = ItemAttribute.PCBANG_EXP_BONUS,
  APPLY_PC_BANG_DROP_BONUS = ItemAttribute.PCBANG_DROP_BONUS,
  APPLY_RESIST_WARRIOR = ItemAttribute.RESIST_WARRIOR,
  APPLY_RESIST_ASSASSIN = ItemAttribute.RESIST_ASSASSIN,
  APPLY_RESIST_SURA = ItemAttribute.RESIST_SURA,
  APPLY_RESIST_SHAMAN = ItemAttribute.RESIST_SHAMAN,
  APPLY_ENERGY = ItemAttribute.ENERGY,
  APPLY_DEF_GRADE = ItemAttribute.DEF_GRADE,
  APPLY_COSTUME_ATTR_BONUS = ItemAttribute.COSTUME_ATTR_BONUS,
  APPLY_MAGIC_ATTBONUS_PER = ItemAttribute.MAGIC_ATTBONUS_PER,
  APPLY_MELEE_MAGIC_ATTBONUS_PER = ItemAttribute.MELEE_MAGIC_ATTBONUS_PER,
  APPLY_RESIST_ICE = ItemAttribute.RESIST_ICE,
  APPLY_RESIST_EARTH = ItemAttribute.RESIST_EARTH,
  APPLY_RESIST_DARK = ItemAttribute.RESIST_DARK,
  APPLY_ANTI_CRITICAL_PCT = ItemAttribute.RESIST_CRITICAL,
  APPLY_ANTI_PENETRATE_PCT = ItemAttribute.RESIST_PENETRATE,

  // VERSION_2022
  // APPLY_BLEEDING_REDUCE = ItemAttribute.BLEEDING_REDUCE,
  // APPLY_BLEEDING_PCT = ItemAttribute.BLEEDING_PCT,
  // APPLY_ATTBONUS_WOLFMAN = ItemAttribute.ATTBONUS_WOLFMAN,
  // APPLY_RESIST_WOLFMAN = ItemAttribute.RESIST_WOLFMAN,
  // APPLY_RESIST_CLAW = ItemAttribute.RESIST_CLAW,
  // APPLY_ACCEDRAIN_RATE = ItemAttribute.ACCEDRAIN_RATE,
  // APPLY_RESIST_MAGIC_REDUCTION = ItemAttribute.RESIST_MAGIC_REDUCTION,
  // APPLY_ENCHANT_ELECT = ItemAttribute.ENCHANT_ELECT,
  // APPLY_ENCHANT_FIRE = ItemAttribute.ENCHANT_FIRE,
  // APPLY_ENCHANT_ICE = ItemAttribute.ENCHANT_ICE,
  // APPLY_ENCHANT_WIND = ItemAttribute.ENCHANT_WIND,
  // APPLY_ENCHANT_EARTH = ItemAttribute.ENCHANT_EARTH,
  // APPLY_ENCHANT_DARK = ItemAttribute.ENCHANT_DARK,
  // APPLY_ATTBONUS_CZ = ItemAttribute.ATTBONUS_CZ,
  // APPLY_ATTBONUS_INSECT = ItemAttribute.ATTBONUS_INSECT,
  // APPLY_ATTBONUS_DESERT = ItemAttribute.ATTBONUS_DESERT,
  // APPLY_ATTBONUS_SWORD = ItemAttribute.ATTBONUS_SWORD,
  // APPLY_ATTBONUS_TWOHAND = ItemAttribute.ATTBONUS_TWOHAND,
  // APPLY_ATTBONUS_DAGGER = ItemAttribute.ATTBONUS_DAGGER,
  // APPLY_ATTBONUS_BELL = ItemAttribute.ATTBONUS_BELL,
  // APPLY_ATTBONUS_FAN = ItemAttribute.ATTBONUS_FAN,
  // APPLY_ATTBONUS_BOW = ItemAttribute.ATTBONUS_BOW,
  // APPLY_ATTBONUS_CLAW = ItemAttribute.ATTBONUS_CLAW,
  // APPLY_RESIST_HUMAN = ItemAttribute.RESIST_HUMAN,
  // APPLY_RESIST_MOUNT_FALL = ItemAttribute.RESIST_MOUNT_FALL,
  // APPLY_RESIST_FIST = ItemAttribute.RESIST_FIST,
  // APPLY_MOUNT = ItemAttribute.MOUNT,
  // APPLY_SKILL_DAMAGE_SAMYEON = ItemAttribute.SKILL_DAMAGE_SAMYEON,
  // APPLY_SKILL_DAMAGE_TANHWAN = ItemAttribute.SKILL_DAMAGE_TANHWAN,
  // APPLY_SKILL_DAMAGE_PALBANG = ItemAttribute.SKILL_DAMAGE_PALBANG,
  // APPLY_SKILL_DAMAGE_GIGONGCHAM = ItemAttribute.SKILL_DAMAGE_GIGONGCHAM,
  // APPLY_SKILL_DAMAGE_GYOKSAN = ItemAttribute.SKILL_DAMAGE_GYOKSAN,
  // APPLY_SKILL_DAMAGE_GEOMPUNG = ItemAttribute.SKILL_DAMAGE_GEOMPUNG,
  // APPLY_SKILL_DAMAGE_AMSEOP = ItemAttribute.SKILL_DAMAGE_AMSEOP,
  // APPLY_SKILL_DAMAGE_GUNGSIN = ItemAttribute.SKILL_DAMAGE_GUNGSIN,
  // APPLY_SKILL_DAMAGE_CHARYUN = ItemAttribute.SKILL_DAMAGE_CHARYUN,
  // APPLY_SKILL_DAMAGE_SANGONG = ItemAttribute.SKILL_DAMAGE_SANGONG,
  // APPLY_SKILL_DAMAGE_YEONSA = ItemAttribute.SKILL_DAMAGE_YEONSA,
  // APPLY_SKILL_DAMAGE_KWANKYEOK = ItemAttribute.SKILL_DAMAGE_KWANKYEOK,
  // APPLY_SKILL_DAMAGE_GIGUNG = ItemAttribute.SKILL_DAMAGE_GIGUNG,
  // APPLY_SKILL_DAMAGE_HWAJO = ItemAttribute.SKILL_DAMAGE_HWAJO,
  // APPLY_SKILL_DAMAGE_SWAERYUNG = ItemAttribute.SKILL_DAMAGE_SWAERYUNG,
  // APPLY_SKILL_DAMAGE_YONGKWON = ItemAttribute.SKILL_DAMAGE_YONGKWON,
  // APPLY_SKILL_DAMAGE_PABEOB = ItemAttribute.SKILL_DAMAGE_PABEOB,
  // APPLY_SKILL_DAMAGE_MARYUNG = ItemAttribute.SKILL_DAMAGE_MARYUNG,
  // APPLY_SKILL_DAMAGE_HWAYEOMPOK = ItemAttribute.SKILL_DAMAGE_HWAYEOMPOK,
  // APPLY_SKILL_DAMAGE_MAHWAN = ItemAttribute.SKILL_DAMAGE_MAHWAN,
  // APPLY_SKILL_DAMAGE_BIPABU = ItemAttribute.SKILL_DAMAGE_BIPABU,
  // APPLY_SKILL_DAMAGE_YONGBI = ItemAttribute.SKILL_DAMAGE_YONGBI,
  // APPLY_SKILL_DAMAGE_PAERYONG = ItemAttribute.SKILL_DAMAGE_PAERYONG,
  // APPLY_SKILL_DAMAGE_NOEJEON = ItemAttribute.SKILL_DAMAGE_NOEJEON,
  // APPLY_SKILL_DAMAGE_BYEURAK = ItemAttribute.SKILL_DAMAGE_BYEURAK,
  // APPLY_SKILL_DAMAGE_CHAIN = ItemAttribute.SKILL_DAMAGE_CHAIN,
  // APPLY_SKILL_DAMAGE_CHAYEOL = ItemAttribute.SKILL_DAMAGE_CHAYEOL,
  // APPLY_SKILL_DAMAGE_SALPOONG = ItemAttribute.SKILL_DAMAGE_SALPOONG,
  // APPLY_SKILL_DAMAGE_GONGDAB = ItemAttribute.SKILL_DAMAGE_GONGDAB,
  // APPLY_SKILL_DAMAGE_PASWAE = ItemAttribute.SKILL_DAMAGE_PASWAE,
  // APPLY_NORMAL_HIT_DEFEND_BONUS_BOSS_OR_MORE = ItemAttribute.NORMAL_HIT_DEFEND_BONUS_BOSS_OR_MORE,
  // APPLY_SKILL_DEFEND_BONUS_BOSS_OR_MORE = ItemAttribute.SKILL_DEFEND_BONUS_BOSS_OR_MORE,
  // APPLY_NORMAL_HIT_DAMAGE_BONUS_BOSS_OR_MORE = ItemAttribute.NORMAL_HIT_DAMAGE_BONUS_BOSS_OR_MORE,
  // APPLY_SKILL_DAMAGE_BONUS_BOSS_OR_MORE = ItemAttribute.SKILL_DAMAGE_BONUS_BOSS_OR_MORE,
  // APPLY_HIT_BUFF_ENCHANT_FIRE = ItemAttribute.HIT_BUFF_ENCHANT_FIRE,
  // APPLY_HIT_BUFF_ENCHANT_ICE = ItemAttribute.HIT_BUFF_ENCHANT_ICE,
  // APPLY_HIT_BUFF_ENCHANT_ELEC = ItemAttribute.HIT_BUFF_ENCHANT_ELEC,
  // APPLY_HIT_BUFF_ENCHANT_WIND = ItemAttribute.HIT_BUFF_ENCHANT_WIND,
  // APPLY_HIT_BUFF_ENCHANT_DARK = ItemAttribute.HIT_BUFF_ENCHANT_DARK,
  // APPLY_HIT_BUFF_ENCHANT_EARTH = ItemAttribute.HIT_BUFF_ENCHANT_EARTH,
  // APPLY_HIT_BUFF_RESIST_FIRE = ItemAttribute.HIT_BUFF_RESIST_FIRE,
  // APPLY_HIT_BUFF_RESIST_ICE = ItemAttribute.HIT_BUFF_RESIST_ICE,
  // APPLY_HIT_BUFF_RESIST_ELEC = ItemAttribute.HIT_BUFF_RESIST_ELEC,
  // APPLY_HIT_BUFF_RESIST_WIND = ItemAttribute.HIT_BUFF_RESIST_WIND,
  // APPLY_HIT_BUFF_RESIST_DARK = ItemAttribute.HIT_BUFF_RESIST_DARK,
  // APPLY_HIT_BUFF_RESIST_EARTH = ItemAttribute.HIT_BUFF_RESIST_EARTH,
  // APPLY_USE_SKILL_CHEONGRANG_MOV_SPEED = ItemAttribute.USE_SKILL_CHEONGRANG_MOV_SPEED,
  // APPLY_USE_SKILL_CHEONGRANG_CASTING_SPEED = ItemAttribute.USE_SKILL_CHEONGRANG_CASTING_SPEED,
  // APPLY_USE_SKILL_CHAYEOL_CRITICAL_PCT = ItemAttribute.USE_SKILL_CHAYEOL_CRITICAL_PCT,
  // APPLY_USE_SKILL_SANGONG_ATT_GRADE_BONUS = ItemAttribute.USE_SKILL_SANGONG_ATT_GRADE_BONUS,
  // APPLY_USE_SKILL_GIGUNG_ATT_GRADE_BONUS = ItemAttribute.USE_SKILL_GIGUNG_ATT_GRADE_BONUS,
  // APPLY_USE_SKILL_JEOKRANG_DEF_BONUS = ItemAttribute.USE_SKILL_JEOKRANG_DEF_BONUS,
  // APPLY_USE_SKILL_GWIGEOM_DEF_BONUS = ItemAttribute.USE_SKILL_GWIGEOM_DEF_BONUS,
  // APPLY_USE_SKILL_TERROR_ATT_GRADE_BONUS = ItemAttribute.USE_SKILL_TERROR_ATT_GRADE_BONUS,
  // APPLY_USE_SKILL_MUYEONG_ATT_GRADE_BONUS = ItemAttribute.USE_SKILL_MUYEONG_ATT_GRADE_BONUS,
  // APPLY_USE_SKILL_MANASHILED_CASTING_SPEED = ItemAttribute.USE_SKILL_MANASHILED_CASTING_SPEED,
  // APPLY_USE_SKILL_HOSIN_DEF_BONUS = ItemAttribute.USE_SKILL_HOSIN_DEF_BONUS,
  // APPLY_USE_SKILL_GICHEON_ATT_GRADE_BONUS = ItemAttribute.USE_SKILL_GICHEON_ATT_GRADE_BONUS,
  // APPLY_USE_SKILL_JEONGEOP_ATT_GRADE_BONUS = ItemAttribute.USE_SKILL_JEONGEOP_ATT_GRADE_BONUS,
  // APPLY_USE_SKILL_JEUNGRYEOK_DEF_BONUS = ItemAttribute.USE_SKILL_JEUNGRYEOK_DEF_BONUS,
  // APPLY_USE_SKILL_GIHYEOL_ATT_GRADE_BONUS = ItemAttribute.USE_SKILL_GIHYEOL_ATT_GRADE_BONUS,
  // APPLY_USE_SKILL_CHUNKEON_CASTING_SPEED = ItemAttribute.USE_SKILL_CHUNKEON_CASTING_SPEED,
  // APPLY_USE_SKILL_NOEGEOM_ATT_GRADE_BONUS = ItemAttribute.USE_SKILL_NOEGEOM_ATT_GRADE_BONUS,
  // APPLY_SKILL_DURATION_INCREASE_EUNHYUNG = ItemAttribute.SKILL_DURATION_INCREASE_EUNHYUNG,
  // APPLY_SKILL_DURATION_INCREASE_GYEONGGONG = ItemAttribute.SKILL_DURATION_INCREASE_GYEONGGONG,
  // APPLY_SKILL_DURATION_INCREASE_GEOMKYUNG = ItemAttribute.SKILL_DURATION_INCREASE_GEOMKYUNG,
  // APPLY_SKILL_DURATION_INCREASE_JEOKRANG = ItemAttribute.SKILL_DURATION_INCREASE_JEOKRANG,
  // APPLY_USE_SKILL_PALBANG_HP_ABSORB = ItemAttribute.USE_SKILL_PALBANG_HP_ABSORB,
  // APPLY_USE_SKILL_AMSEOP_HP_ABSORB = ItemAttribute.USE_SKILL_AMSEOP_HP_ABSORB,
  // APPLY_USE_SKILL_YEONSA_HP_ABSORB = ItemAttribute.USE_SKILL_YEONSA_HP_ABSORB,
  // APPLY_USE_SKILL_YONGBI_HP_ABSORB = ItemAttribute.USE_SKILL_YONGBI_HP_ABSORB,
  // APPLY_USE_SKILL_CHAIN_HP_ABSORB = ItemAttribute.USE_SKILL_CHAIN_HP_ABSORB,
  // APPLY_USE_SKILL_PASWAE_SP_ABSORB = ItemAttribute.USE_SKILL_PASWAE_SP_ABSORB,
  // APPLY_USE_SKILL_GIGONGCHAM_STUN = ItemAttribute.USE_SKILL_GIGONGCHAM_STUN,
  // APPLY_USE_SKILL_CHARYUN_STUN = ItemAttribute.USE_SKILL_CHARYUN_STUN,
  // APPLY_USE_SKILL_PABEOB_STUN = ItemAttribute.USE_SKILL_PABEOB_STUN,
  // APPLY_USE_SKILL_MAHWAN_STUN = ItemAttribute.USE_SKILL_MAHWAN_STUN,
  // APPLY_USE_SKILL_GONGDAB_STUN = ItemAttribute.USE_SKILL_GONGDAB_STUN,
  // APPLY_USE_SKILL_SAMYEON_STUN = ItemAttribute.USE_SKILL_SAMYEON_STUN,
  // APPLY_USE_SKILL_GYOKSAN_KNOCKBACK = ItemAttribute.USE_SKILL_GYOKSAN_KNOCKBACK,
  // APPLY_USE_SKILL_SEOMJEON_KNOCKBACK = ItemAttribute.USE_SKILL_SEOMJEON_KNOCKBACK,
  // APPLY_USE_SKILL_SWAERYUNG_KNOCKBACK = ItemAttribute.USE_SKILL_SWAERYUNG_KNOCKBACK,
  // APPLY_USE_SKILL_HWAYEOMPOK_KNOCKBACK = ItemAttribute.USE_SKILL_HWAYEOMPOK_KNOCKBACK,
  // APPLY_USE_SKILL_GONGDAB_KNOCKBACK = ItemAttribute.USE_SKILL_GONGDAB_KNOCKBACK,
  // APPLY_USE_SKILL_KWANKYEOK_KNOCKBACK = ItemAttribute.USE_SKILL_KWANKYEOK_KNOCKBACK,
  // APPLY_USE_SKILL_SAMYEON_NEXT_COOLTIME_DECREASE_10PER = ItemAttribute.USE_SKILL_SAMYEON_NEXT_COOLTIME_DECREASE_10PER,
  // APPLY_USE_SKILL_GEOMPUNG_NEXT_COOLTIME_DECREASE_10PER = ItemAttribute.USE_SKILL_GEOMPUNG_NEXT_COOLTIME_DECREASE_10PER,
  // APPLY_USE_SKILL_GUNGSIN_NEXT_COOLTIME_DECREASE_10PER = ItemAttribute.USE_SKILL_GUNGSIN_NEXT_COOLTIME_DECREASE_10PER,
  // APPLY_USE_SKILL_KWANKYEOK_NEXT_COOLTIME_DECREASE_10PER = ItemAttribute.USE_SKILL_KWANKYEOK_NEXT_COOLTIME_DECREASE_10PER,
  // APPLY_USE_SKILL_YONGKWON_NEXT_COOLTIME_DECREASE_10PER = ItemAttribute.USE_SKILL_YONGKWON_NEXT_COOLTIME_DECREASE_10PER,
  // APPLY_USE_SKILL_MARYUNG_NEXT_COOLTIME_DECREASE_10PER = ItemAttribute.USE_SKILL_MARYUNG_NEXT_COOLTIME_DECREASE_10PER,
  // APPLY_USE_SKILL_BIPABU_NEXT_COOLTIME_DECREASE_10PER = ItemAttribute.USE_SKILL_BIPABU_NEXT_COOLTIME_DECREASE_10PER,
  // APPLY_USE_SKILL_NOEJEON_NEXT_COOLTIME_DECREASE_10PER = ItemAttribute.USE_SKILL_NOEJEON_NEXT_COOLTIME_DECREASE_10PER,
  // APPLY_USE_SKILL_SALPOONG_NEXT_COOLTIME_DECREASE_10PER = ItemAttribute.USE_SKILL_SALPOONG_NEXT_COOLTIME_DECREASE_10PER,
  // APPLY_USE_SKILL_PASWAE_NEXT_COOLTIME_DECREASE_10PER = ItemAttribute.USE_SKILL_PASWAE_NEXT_COOLTIME_DECREASE_10PER,
  // APPLY_ATTBONUS_STONE = ItemAttribute.ATTBONUS_STONE,
  // APPLY_DAMAGE_HP_RECOVERY = ItemAttribute.DAMAGE_HP_RECOVERY,
  // APPLY_DAMAGE_SP_RECOVERY = ItemAttribute.DAMAGE_SP_RECOVERY,
  // APPLY_ALIGNMENT_DAMAGE_BONUS = ItemAttribute.ALIGNMENT_DAMAGE_BONUS,
  // APPLY_NORMAL_DAMAGE_GUARD = ItemAttribute.NORMAL_DAMAGE_GUARD,
  // APPLY_MORE_THEN_HP90_DAMAGE_REDUCE = ItemAttribute.MORE_THEN_HP90_DAMAGE_REDUCE,
  // APPLY_USE_SKILL_TUSOK_HP_ABSORB = ItemAttribute.USE_SKILL_TUSOK_HP_ABSORB,
  // APPLY_USE_SKILL_PAERYONG_HP_ABSORB = ItemAttribute.USE_SKILL_PAERYONG_HP_ABSORB,
  // APPLY_USE_SKILL_BYEURAK_HP_ABSORB = ItemAttribute.USE_SKILL_BYEURAK_HP_ABSORB,
  // APPLY_FIRST_ATTRIBUTE_BONUS = ItemAttribute.FIRST_ATTRIBUTE_BONUS,
  // APPLY_SECOND_ATTRIBUTE_BONUS = ItemAttribute.SECOND_ATTRIBUTE_BONUS,
  // APPLY_THIRD_ATTRIBUTE_BONUS = ItemAttribute.THIRD_ATTRIBUTE_BONUS,
  // APPLY_FOURTH_ATTRIBUTE_BONUS = ItemAttribute.FOURTH_ATTRIBUTE_BONUS,
  // APPLY_FIFTH_ATTRIBUTE_BONUS = ItemAttribute.FIFTH_ATTRIBUTE_BONUS,
  // APPLY_USE_SKILL_SAMYEON_NEXT_COOLTIME_DECREASE_20PER = ItemAttribute.USE_SKILL_SAMYEON_NEXT_COOLTIME_DECREASE_20PER,
  // APPLY_USE_SKILL_GEOMPUNG_NEXT_COOLTIME_DECREASE_20PER = ItemAttribute.USE_SKILL_GEOMPUNG_NEXT_COOLTIME_DECREASE_20PER,
  // APPLY_USE_SKILL_GUNGSIN_NEXT_COOLTIME_DECREASE_20PER = ItemAttribute.USE_SKILL_GUNGSIN_NEXT_COOLTIME_DECREASE_20PER,
  // APPLY_USE_SKILL_KWANKYEOK_NEXT_COOLTIME_DECREASE_20PER = ItemAttribute.USE_SKILL_KWANKYEOK_NEXT_COOLTIME_DECREASE_20PER,
  // APPLY_USE_SKILL_YONGKWON_NEXT_COOLTIME_DECREASE_20PER = ItemAttribute.USE_SKILL_YONGKWON_NEXT_COOLTIME_DECREASE_20PER,
  // APPLY_USE_SKILL_MARYUNG_NEXT_COOLTIME_DECREASE_20PER = ItemAttribute.USE_SKILL_MARYUNG_NEXT_COOLTIME_DECREASE_20PER,
  // APPLY_USE_SKILL_BIPABU_NEXT_COOLTIME_DECREASE_20PER = ItemAttribute.USE_SKILL_BIPABU_NEXT_COOLTIME_DECREASE_20PER,
  // APPLY_USE_SKILL_NOEJEON_NEXT_COOLTIME_DECREASE_20PER = ItemAttribute.USE_SKILL_NOEJEON_NEXT_COOLTIME_DECREASE_20PER,
  // APPLY_USE_SKILL_SALPOONG_NEXT_COOLTIME_DECREASE_20PER = ItemAttribute.USE_SKILL_SALPOONG_NEXT_COOLTIME_DECREASE_20PER,
  // APPLY_USE_SKILL_PASWAE_NEXT_COOLTIME_DECREASE_20PER = ItemAttribute.USE_SKILL_PASWAE_NEXT_COOLTIME_DECREASE_20PER,
  // APPLY_USE_SKILL_CHAYEOL_HP_ABSORB = ItemAttribute.USE_SKILL_CHAYEOL_HP_ABSORB,
  // APPLY_SUNGMA_STR = ItemAttribute.SUNGMA_STR,
  // APPLY_SUNGMA_HP = ItemAttribute.SUNGMA_HP,
  // APPLY_SUNGMA_MOVE = ItemAttribute.SUNGMA_MOVE,
  // APPLY_SUNGMA_IMMUNE = ItemAttribute.SUNGMA_IMMUNE,
  // APPLY_HIT_PCT = ItemAttribute.HIT_PCT,
  // APPLY_RANDOM = ItemAttribute.RANDOM,
  // APPLY_ATTBONUS_PER_HUMAN = ItemAttribute.ATTBONUS_PER_HUMAN,
  // APPLY_ATTBONUS_PER_ANIMAL = ItemAttribute.ATTBONUS_PER_ANIMAL,
  // APPLY_ATTBONUS_PER_ORC = ItemAttribute.ATTBONUS_PER_ORC,
  // APPLY_ATTBONUS_PER_MILGYO = ItemAttribute.ATTBONUS_PER_MILGYO,
  // APPLY_ATTBONUS_PER_UNDEAD = ItemAttribute.ATTBONUS_PER_UNDEAD,
  // APPLY_ATTBONUS_PER_DEVIL = ItemAttribute.ATTBONUS_PER_DEVIL,
  // APPLY_ENCHANT_PER_ELECT = ItemAttribute.ENCHANT_PER_ELECT,
  // APPLY_ENCHANT_PER_FIRE = ItemAttribute.ENCHANT_PER_FIRE,
  // APPLY_ENCHANT_PER_ICE = ItemAttribute.ENCHANT_PER_ICE,
  // APPLY_ENCHANT_PER_WIND = ItemAttribute.ENCHANT_PER_WIND,
  // APPLY_ENCHANT_PER_EARTH = ItemAttribute.ENCHANT_PER_EARTH,
  // APPLY_ENCHANT_PER_DARK = ItemAttribute.ENCHANT_PER_DARK,
  // APPLY_ATTBONUS_PER_CZ = ItemAttribute.ATTBONUS_PER_CZ,
  // APPLY_ATTBONUS_PER_INSECT = ItemAttribute.ATTBONUS_PER_INSECT,
  // APPLY_ATTBONUS_PER_DESERT = ItemAttribute.ATTBONUS_PER_DESERT,
  // APPLY_ATTBONUS_PER_STONE = ItemAttribute.ATTBONUS_PER_STONE,
  // APPLY_ATTBONUS_PER_MONSTER = ItemAttribute.ATTBONUS_PER_MONSTER,
  // APPLY_RESIST_PER_HUMAN = ItemAttribute.RESIST_PER_HUMAN,
  // APPLY_RESIST_PER_ICE = ItemAttribute.RESIST_PER_ICE,
  // APPLY_RESIST_PER_DARK = ItemAttribute.RESIST_PER_DARK,
  // APPLY_RESIST_PER_EARTH = ItemAttribute.RESIST_PER_EARTH,
  // APPLY_RESIST_PER_FIRE = ItemAttribute.RESIST_PER_FIRE,
  // APPLY_RESIST_PER_ELEC = ItemAttribute.RESIST_PER_ELEC,
  // APPLY_RESIST_PER_MAGIC = ItemAttribute.RESIST_PER_MAGIC,
  // APPLY_RESIST_PER_WIND = ItemAttribute.RESIST_PER_WIND,
  // APPLY_HIT_BUFF_SUNGMA_STR = ItemAttribute.HIT_BUFF_SUNGMA_STR,
  // APPLY_HIT_BUFF_SUNGMA_MOVE = ItemAttribute.HIT_BUFF_SUNGMA_MOVE,
  // APPLY_HIT_BUFF_SUNGMA_HP = ItemAttribute.HIT_BUFF_SUNGMA_HP,
  // APPLY_HIT_BUFF_SUNGMA_IMMUNE = ItemAttribute.HIT_BUFF_SUNGMA_IMMUNE,
  // APPLY_MOUNT_MELEE_MAGIC_ATTBONUS_PER = ItemAttribute.MOUNT_MELEE_MAGIC_ATTBONUS_PER,
  // APPLY_DISMOUNT_MOVE_SPEED_BONUS_PER = ItemAttribute.DISMOUNT_MOVE_SPEED_BONUS_PER,
  // APPLY_HIT_AUTO_HP_RECOVERY = ItemAttribute.HIT_AUTO_HP_RECOVERY,
  // APPLY_HIT_AUTO_SP_RECOVERY = ItemAttribute.HIT_AUTO_SP_RECOVERY,
  // APPLY_USE_SKILL_COOLTIME_DECREASE_ALL = ItemAttribute.USE_SKILL_COOLTIME_DECREASE_ALL,
  // APPLY_HIT_STONE_ATTBONUS_STONE = ItemAttribute.HIT_STONE_ATTBONUS_STONE,
  // APPLY_HIT_STONE_DEF_GRADE_BONUS = ItemAttribute.HIT_STONE_DEF_GRADE_BONUS,
  // APPLY_KILL_BOSS_ITEM_BONUS = ItemAttribute.KILL_BOSS_ITEM_BONUS,
  // APPLY_MOB_HIT_MOB_AGGRESSIVE = ItemAttribute.MOB_HIT_MOB_AGGRESSIVE,
  // APPLY_NO_DEATH_AND_HP_RECOVERY30 = ItemAttribute.NO_DEATH_AND_HP_RECOVERY30,
  // APPLY_AUTO_PICKUP = ItemAttribute.AUTO_PICKUP,
  // APPLY_MOUNT_NO_KNOCKBACK = ItemAttribute.MOUNT_NO_KNOCKBACK,
  // APPLY_SUNGMA_PER_STR = ItemAttribute.SUNGMA_PER_STR,
  // APPLY_SUNGMA_PER_HP = ItemAttribute.SUNGMA_PER_HP,
  // APPLY_SUNGMA_PER_MOVE = ItemAttribute.SUNGMA_PER_MOVE,
  // APPLY_SUNGMA_PER_IMMUNE = ItemAttribute.SUNGMA_PER_IMMUNE,
  // APPLY_IMMUNE_POISON100 = ItemAttribute.IMMUNE_POISON100,
  // APPLY_IMMUNE_BLEEDING100 = ItemAttribute.IMMUNE_BLEEDING100,
  // APPLY_MONSTER_DEFEND_BONUS = ItemAttribute.MONSTER_DEFEND_BONUS,
}


/*****************************************************************************
 * Mask types
 *****************************************************************************/
export enum GameItemProtoMaskType {
  MASK_ITEM_TYPE_NONE = ItemMaskType.NONE,
  MASK_ITEM_TYPE_MOUNT_PET = ItemMaskType.MOUNT_PET,
  MASK_ITEM_TYPE_EQUIPMENT_WEAPON = ItemMaskType.EQUIPMENT_WEAPON,
  MASK_ITEM_TYPE_EQUIPMENT_ARMOR = ItemMaskType.EQUIPMENT_ARMOR,
  MASK_ITEM_TYPE_EQUIPMENT_JEWELRY = ItemMaskType.EQUIPMENT_JEWELRY,
  MASK_ITEM_TYPE_TUNING = ItemMaskType.TUNING,
  MASK_ITEM_TYPE_POTION = ItemMaskType.POTION,
  MASK_ITEM_TYPE_FISHING_PICK = ItemMaskType.FISHING_PICK,
  MASK_ITEM_TYPE_DRAGON_STONE = ItemMaskType.DRAGON_STONE,
  MASK_ITEM_TYPE_COSTUMES = ItemMaskType.COSTUMES,
  MASK_ITEM_TYPE_SKILL = ItemMaskType.SKILL,
  MASK_ITEM_TYPE_UNIQUE = ItemMaskType.UNIQUE,
  MASK_ITEM_TYPE_ETC = ItemMaskType.ETC,
}


/*****************************************************************************
 * Mask subtypes
 *****************************************************************************/
export enum GameItemProtoMaskTypeMountPet {
  MASK_ITEM_SUBTYPE_MOUNT_PET_MOUNT = ItemMaskTypeMountPet.MOUNT,
  MASK_ITEM_SUBTYPE_MOUNT_PET_CHARGED_PET = ItemMaskTypeMountPet.CHARGED_PET,
  MASK_ITEM_SUBTYPE_MOUNT_PET_FREE_PET = ItemMaskTypeMountPet.FREE_PET,
  MASK_ITEM_SUBTYPE_MOUNT_PET_EGG = ItemMaskTypeMountPet.EGG,
}

export enum GameItemProtoMaskTypeEquipmentWeapon {
  MASK_ITEM_SUBTYPE_WEAPON_WEAPON_SWORD = ItemMaskTypeEquipmentWeapon.SWORD,
  MASK_ITEM_SUBTYPE_WEAPON_WEAPON_DAGGER = ItemMaskTypeEquipmentWeapon.DAGGER,
  MASK_ITEM_SUBTYPE_WEAPON_WEAPON_BOW = ItemMaskTypeEquipmentWeapon.BOW,
  MASK_ITEM_SUBTYPE_WEAPON_WEAPON_TWO_HANDED = ItemMaskTypeEquipmentWeapon.TWO_HANDED,
  MASK_ITEM_SUBTYPE_WEAPON_WEAPON_BELL = ItemMaskTypeEquipmentWeapon.BELL,
  MASK_ITEM_SUBTYPE_WEAPON_WEAPON_CLAW = ItemMaskTypeEquipmentWeapon.CLAW,
  MASK_ITEM_SUBTYPE_WEAPON_WEAPON_FAN = ItemMaskTypeEquipmentWeapon.FAN,
  MASK_ITEM_SUBTYPE_WEAPON_WEAPON_MOUNT_SPEAR = ItemMaskTypeEquipmentWeapon.MOUNT_SPEAR,
  MASK_ITEM_SUBTYPE_WEAPON_WEAPON_ARROW = ItemMaskTypeEquipmentWeapon.ARROW,
}

export enum GameItemProtoMaskTypeEquipmentArmor {
  MASK_ITEM_SUBTYPE_ARMOR_ARMOR_BODY = ItemMaskTypeEquipmentArmor.BODY,
  MASK_ITEM_SUBTYPE_ARMOR_ARMOR_GLOVE = ItemMaskTypeEquipmentArmor.GLOVE,
  MASK_ITEM_SUBTYPE_ARMOR_ARMOR_HEAD = ItemMaskTypeEquipmentArmor.HEAD,
  MASK_ITEM_SUBTYPE_ARMOR_ARMOR_SHIELD = ItemMaskTypeEquipmentArmor.SHIELD,
}

export enum GameItemProtoMaskTypeEquipmentJewelry {
  MASK_ITEM_SUBTYPE_JEWELRY_ARMOR_WRIST = ItemMaskTypeEquipmentJewelry.ARMOR_WRIST,
  MASK_ITEM_SUBTYPE_JEWELRY_ARMOR_FOOTS = ItemMaskTypeEquipmentJewelry.ARMOR_FOOTS,
  MASK_ITEM_SUBTYPE_JEWELRY_ARMOR_NECK = ItemMaskTypeEquipmentJewelry.ARMOR_NECK,
  MASK_ITEM_SUBTYPE_JEWELRY_ARMOR_EAR = ItemMaskTypeEquipmentJewelry.ARMOR_EAR,
  MASK_ITEM_SUBTYPE_JEWELRY_ITEM_BELT = ItemMaskTypeEquipmentJewelry.ITEM_BELT,
  MASK_ITEM_SUBTYPE_JEWELRY_ARMOR_PENDANT = ItemMaskTypeEquipmentJewelry.ARMOR_PENDANT,
}

export enum GameItemProtoMaskTypeTuning {
  MASK_ITEM_SUBTYPE_TUNING_RESOURCE = ItemMaskTypeTuning.RESOURCE,
  MASK_ITEM_SUBTYPE_TUNING_STONE = ItemMaskTypeTuning.STONE,
  MASK_ITEM_SUBTYPE_TUNING_ETC = ItemMaskTypeTuning.ETC,
}

export enum GameItemProtoMaskTypePotion {
  MASK_ITEM_SUBTYPE_POTION_ABILITY = ItemMaskTypePotion.ABILITY,
  MASK_ITEM_SUBTYPE_POTION_HAIRDYE = ItemMaskTypePotion.HAIRDYE,
  MASK_ITEM_SUBTYPE_POTION_ETC = ItemMaskTypePotion.ETC,
}

export enum GameItemProtoMaskTypeFishingPick {
  MASK_ITEM_SUBTYPE_FISHING_PICK_FISHING_POLE = ItemMaskTypeFishingPick.FISHING_POLE,
  MASK_ITEM_SUBTYPE_FISHING_PICK_EQUIPMENT_PICK = ItemMaskTypeFishingPick.EQUIPMENT_PICK,
  MASK_ITEM_SUBTYPE_FISHING_PICK_FOOD = ItemMaskTypeFishingPick.FOOD,
  MASK_ITEM_SUBTYPE_FISHING_PICK_STONE = ItemMaskTypeFishingPick.STONE,
  MASK_ITEM_SUBTYPE_FISHING_PICK_ETC = ItemMaskTypeFishingPick.ETC,
}

export enum GameItemProtoMaskTypeDragonStone {
  MASK_ITEM_SUBTYPE_DRAGON_STONE_DRAGON_DIAMOND = ItemMaskTypeDragonStone.DRAGON_DIAMOND,
  MASK_ITEM_SUBTYPE_DRAGON_STONE_DRAGON_RUBY = ItemMaskTypeDragonStone.DRAGON_RUBY,
  MASK_ITEM_SUBTYPE_DRAGON_STONE_DRAGON_JADE = ItemMaskTypeDragonStone.DRAGON_JADE,
  MASK_ITEM_SUBTYPE_DRAGON_STONE_DRAGON_SAPPHIRE = ItemMaskTypeDragonStone.DRAGON_SAPPHIRE,
  MASK_ITEM_SUBTYPE_DRAGON_STONE_DRAGON_GARNET = ItemMaskTypeDragonStone.DRAGON_GARNET,
  MASK_ITEM_SUBTYPE_DRAGON_STONE_DRAGON_ONYX = ItemMaskTypeDragonStone.DRAGON_ONYX,
  MASK_ITEM_SUBTYPE_DRAGON_STONE_ETC = ItemMaskTypeDragonStone.ETC,
}

export enum GameItemProtoMaskTypeCostume {
  MASK_ITEM_SUBTYPE_COSTUMES_COSTUME_WEAPON = ItemMaskTypeCostume.COSTUME_WEAPON,
  MASK_ITEM_SUBTYPE_COSTUMES_COSTUME_BODY = ItemMaskTypeCostume.COSTUME_BODY,
  MASK_ITEM_SUBTYPE_COSTUMES_COSTUME_HAIR = ItemMaskTypeCostume.COSTUME_HAIR,
  MASK_ITEM_SUBTYPE_COSTUMES_SASH = ItemMaskTypeCostume.SASH,
  MASK_ITEM_SUBTYPE_COSTUMES_ETC = ItemMaskTypeCostume.ETC,
  MASK_ITEM_SUBTYPE_COSTUMES_AURA = ItemMaskTypeCostume.AURA,
}

export enum GameItemProtoMaskTypeSkill {
  MASK_ITEM_SUBTYPE_SKILL_PAHAE = ItemMaskTypeSkill.PAHAE,
  MASK_ITEM_SUBTYPE_SKILL_SKILL_BOOK = ItemMaskTypeSkill.SKILL_BOOK,
  MASK_ITEM_SUBTYPE_SKILL_BOOK_OF_OBLIVION = ItemMaskTypeSkill.BOOK_OF_OBLIVION,
  MASK_ITEM_SUBTYPE_SKILL_ETC = ItemMaskTypeSkill.ETC,
  MASK_ITEM_SUBTYPE_SKILL_SKILL_BOOK_HORSE = ItemMaskTypeSkill.SKILL_BOOK_HORSE,
}

export enum GameItemProtoMaskTypeUnique {
  MASK_ITEM_SUBTYPE_UNIQUE_ABILITY = ItemMaskTypeUnique.ABILITY,
  MASK_ITEM_SUBTYPE_UNIQUE_ETC = ItemMaskTypeUnique.ETC,
}

export enum GameItemProtoMaskTypeEtc {
  MASK_ITEM_SUBTYPE_ETC_GIFTBOX = ItemMaskTypeEtc.GIFTBOX,
  MASK_ITEM_SUBTYPE_ETC_MATRIMORY = ItemMaskTypeEtc.MATRIMORY,
  MASK_ITEM_SUBTYPE_ETC_EVENT = ItemMaskTypeEtc.EVENT,
  MASK_ITEM_SUBTYPE_ETC_SEAL = ItemMaskTypeEtc.SEAL,
  MASK_ITEM_SUBTYPE_ETC_PARTI = ItemMaskTypeEtc.PARTI,
  MASK_ITEM_SUBTYPE_ETC_POLYMORPH = ItemMaskTypeEtc.POLYMORPH,
  MASK_ITEM_SUBTYPE_ETC_RECIPE = ItemMaskTypeEtc.RECIPE,
  MASK_ITEM_SUBTYPE_ETC_ETC = ItemMaskTypeEtc.ETC,
}

export const GameItemProtoMaskTypeSubTypes = {
  [GameItemProtoMaskType.MASK_ITEM_TYPE_NONE]: {},
  [GameItemProtoMaskType.MASK_ITEM_TYPE_MOUNT_PET]: GameItemProtoMaskTypeMountPet,
  [GameItemProtoMaskType.MASK_ITEM_TYPE_EQUIPMENT_WEAPON]: GameItemProtoMaskTypeEquipmentWeapon,
  [GameItemProtoMaskType.MASK_ITEM_TYPE_EQUIPMENT_ARMOR]: GameItemProtoMaskTypeEquipmentArmor,
  [GameItemProtoMaskType.MASK_ITEM_TYPE_EQUIPMENT_JEWELRY]: GameItemProtoMaskTypeEquipmentJewelry,
  [GameItemProtoMaskType.MASK_ITEM_TYPE_TUNING]: GameItemProtoMaskTypeTuning,
  [GameItemProtoMaskType.MASK_ITEM_TYPE_POTION]: GameItemProtoMaskTypePotion,
  [GameItemProtoMaskType.MASK_ITEM_TYPE_FISHING_PICK]: GameItemProtoMaskTypeFishingPick,
  [GameItemProtoMaskType.MASK_ITEM_TYPE_DRAGON_STONE]: GameItemProtoMaskTypeDragonStone,
  [GameItemProtoMaskType.MASK_ITEM_TYPE_COSTUMES]: GameItemProtoMaskTypeCostume,
  [GameItemProtoMaskType.MASK_ITEM_TYPE_SKILL]: GameItemProtoMaskTypeSkill,
  [GameItemProtoMaskType.MASK_ITEM_TYPE_UNIQUE]: GameItemProtoMaskTypeUnique,
  [GameItemProtoMaskType.MASK_ITEM_TYPE_ETC]: GameItemProtoMaskTypeEtc,
}